### PR TITLE
Parent with SoftDeletes bug

### PR DESCRIPTION
**Pull request by axlon**
This PR fixes a bug that causes the BelongsToThrough relation to never return any results when the parent model is soft deleted.

Imagine the following scenario:

model A (uses SoftDeletes)
- belongsTo B
- belongsToThrough C

model B
- belongsTo C

model C

If model A has soft deletes the relation will currently generate the following query:

```mysql
select `c`.*
from `c`
left join `b` on `c`.`id` = `b`.`c_id`
left join `a` on `b`.`id` = `a`.`b_id`
where `a`.`id` = ? and `a`.`id` is not null and `a`.`deleted_at` is null
```

After this PR the relation will generate the following query:

```mysql
select `c`.*
from `c`
left join `b` on `c`.`id` = `b`.`c_id`
left join `a` on `b`.`id` = `a`.`b_id`
where `a`.`id` = ? and `a`.`id` is not null
```

Note that any models that are not the parent will still have soft delete checks added to the query if they use the SoftDeletes trait.

### CODE REVIEW

**Comment by znck** [comment]
Looking for maintainers. #32

**Comment by staudenmeir** [comment]
Thanks, I'll take a look at it in the next days.

**Comment by axlon** [comment]
@staudenmeir any update?

**Comment by staudenmeir** [comment]
Sorry, still working on the next version. I'll release it this week.

**Comment by staudenmeir** [comment]
Thanks!

**Pull request merged**
